plugins {
    id 'multiloader-api'
    id 'maven-publish'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.1.0'
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = mod_id + '-common-api-' + minecraft_version
            from components.java
        }
    }
    repositories {
        maven {
            url = 'https://nexus.magnusjensen.dk/repository/maven-releases/'

            credentials {
                username = System.getenv('NEXUS_USERNAME') ?: ''
                password = System.getenv('NEXUS_PASSWORD') ?: ''
            }
        }
    }
}